"use client";
import React, { useContext, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { useAuthContext } from "../context/AuthContext";
import styles from "../styles/Home.module.css";
import Head from "next/head";
import CheckDate from "./components/CheckDate/CheckDate";
import CheckTime from "./components/CheckTime/CheckTime";
import { User_data } from "../context/Context";
import Navigation from "./components/Navigation/Navigation";

function MakeBooking() {
  const [step, setStep] = useState("date");
  const [loading, setLoading] = useState("")
  const [error, setError] = useState()
  const [bookingData, setBookingData] = useState()

  const { user } = useAuthContext();
  const { userData, setUserData } = useContext(User_data);
  console.log(userData)
  
  const router = useRouter();
  useEffect(() => {
    if (!user) {
      router.push("/login")
    }
  }, [user])
  // check date in the database, save in context the query and move to next step
  async function checkData(e, date) {
    setLoading(true)
    e.preventDefault();
    try {
      const response = await fetch("/api/checkDate", {
        method: "POST",
        body: JSON.stringify({
          date: date,
        }),
      });
      const responseData = await response.json();
      setBookingData(responseData)
      setLoading("")
      setStep("time");
    } catch (error) {
      setLoading("")
      setError(error)
      console.log(error);
    }
  }



  return (
    <div className={styles.outer_container}>
      <Head>
        <title>Booking</title>
        <meta name="description" content="Generated by JW Digital" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.container}>
        <section className={styles.inner_container}>
          <Navigation/>
          <h1 className={styles.title}>Book a table</h1>
          {loading && <div
          style={{
            display:"flex",
            justifyContent: "center",
            marginTop: "100px"
          }}
          ><div className="loader"/></div>}

          {step === "date" && loading !== true && <CheckDate checkData={checkData} />}
          {step === "time" && loading !== true && <CheckTime bookingData={bookingData}/>}
        </section>
        <div className="creds">
          <div>
            Powered by <a href="https://jw-digital.co.uk">JW Digital</a>
          </div>
        </div>
      </main>
    </div>
  );
}

export default MakeBooking;
