"use client";
import React, { useContext, useState } from "react";
import { useRouter } from "next/navigation";
import { useAuthContext } from "../context/AuthContext";
import styles from "../styles/Home.module.css";
import Head from "next/head";
import CheckDate from "./components/CheckDate/CheckDate";
import CheckTime from "./components/CheckTime/CheckTime";
import { User_data } from "../context/Context";
import Navigation from "./components/Navigation/Navigation";

function MakeBooking() {
  const [step, setStep] = useState("date");

  const { user } = useAuthContext();
  const { userData, setUserData } = useContext(User_data);
  const router = useRouter();
  // check date in the database, save in context the query and move to next step
  async function checkData(e, date) {
    e.preventDefault();
    try {
      const response = await fetch("/api/checkDate", {
        method: "POST",
        body: JSON.stringify({
          date: date,
        }),
      });
      const responseData = await response.json();
      setUserData([
        { ...userData, booking_date: date, booking_date_id: responseData.id },
        responseData,
      ]);
      setStep("time");
    } catch (error) {
      console.log(error);
    }
  }

  //

  function submitBooking() {}

  return (
    <div className={styles.outer_container}>
      <Head>
        <title>Booking</title>
        <meta name="description" content="Generated by JW Digital" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.container}>
        <section className={styles.inner_container}>
          <Navigation/>
          <h1 className={styles.title}>Book a table</h1>

          {step === "date" && <CheckDate checkData={checkData} />}
          {step === "time" && <CheckTime />}
        </section>
        <div className="creds">
          <div>
            Powered by <a href="https://jw-digital.co.uk">JW Digital</a>
          </div>
        </div>
      </main>
    </div>
  );
}

export default MakeBooking;
