'use client'
import React, { useEffect } from "react";
import { useRouter } from "next/navigation";
import { useAuthContext } from "./context/AuthContext";
import styles from "../styles/Home.module.css";
import Head from "next/head";

function Page() {
    const { user } = useAuthContext()
    const router = useRouter()
    console.log(user)
    useEffect(() => {
        if (user == null) router.push("/login")
    }, [user])

    return (
      <div className={styles.outer_container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.container}>
        <section className={styles.inner_container}>
          <h1 className={styles.title}></h1>
        </section>
      </main>
    </div>
    );
}

export default Page;