"use client";
import styles from "../styles/Home.module.css";
import Head from "next/head";
import { useContext } from "react";
import Context, { User_data } from "../context/Context";
import Navigation from "./components/Navigation/Navigation";

function Page() {
  const { userData } = useContext(User_data);
  console.log(userData);

  return (
    <div className={styles.outer_container}>
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by JW Digital" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.container}>
        <section className={styles.inner_container}>
          <Navigation/>
          <h1 style={{
            marginTop: "60px",
            textAlign:"center"
          }}>Dashboard</h1>

        </section>
        <div className="creds">
          <div>
            Powered by <a href="https://jw-digital.co.uk">JW Digital</a>
          </div>
        </div>
      </main>
    </div>
  );
}

export default Page;
