import Head from 'next/head';
import React, { useContext } from 'react'
import styles from "../styles/Home.module.css";
import Navigation from './components/Navigation/Navigation';
import { User_data } from "../context/Context";


function mybookings() {
  const { userData } = useContext(User_data);
  console.log(userData)

  return (
    <div className={styles.outer_container}>
    <Head>
      <title>Login</title>
      <meta name="description" content="Generated by JW Digital" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <main className={styles.container}>
      <section className={styles.inner_container}>
      <Navigation/>
      <h1 className={styles.title}>Bookings</h1>
      <ul className={styles.bookings_list}>
      {
        userData.bookings.length >= 1 && userData.bookings.map((item, index) => (
          <li className={styles.bookings_list_item}>
            <h3>{item.booking_date}</h3>
            <p>Booking at {item.booking_time} for {item.guests} guests.</p>
            <button>Make a change</button>
            <button>Cancel Booking</button>
          </li>
        ))
      }
      </ul>
      </section>
      </main>
      </div>
  )
}

export default mybookings