import Head from 'next/head';
import React, { useContext, useEffect } from 'react'
import styles from "../styles/Home.module.css";
import Navigation from './components/Navigation/Navigation';
import { User_data } from "../context/Context";
import { useAuthContext } from '../context/AuthContext';
import { useRouter } from 'next/router';
import Item from './components/MyBookings/Item';


function mybookings() {
  const { userData, setUserData } = useContext(User_data);
  const { user } = useAuthContext();
  const router = useRouter()

  useEffect(() => {
    if (!user) {
      router.push("/login")
    }
  }, [user])
  useEffect(() => {
    const fetchData = async () => {
      if (user) {
        try {
          const response = await fetch("/api/pullUserBookings", {
            method: "POST",
            body: JSON.stringify({
              email: user.email
            }),
          });
          const responseData = await response.json();
          setUserData(prevUserData => ({
            ...prevUserData,
            bookings: responseData.bookings
          }));
        } catch (error) {
          console.error("Error fetching data:", error);
        }
      }
    };
  
    fetchData();
  }, []);
  console.log(userData)

  return (
    <div className={styles.outer_container}>
    <Head>
      <title>Login</title>
      <meta name="description" content="Generated by JW Digital" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <main className={styles.container}>
      <section className={styles.inner_container}>
      <Navigation/>
      <h1 className={styles.title}>Bookings</h1>
      <ul className={styles.bookings_list}>
      {
        userData.bookings && userData.bookings.map((item, index) => (
          <Item item={item} index={index}/>
        ))
      }
      </ul>
      </section>
      </main>
      </div>
  )
}

export default mybookings